

import SwiftUI

struct Asmaa: Identifiable, Codable {
    var isFaved: Bool
    var id: Int
    var name: String
    var arabic: String
    var shortText: String
    var description: String

    static var Name: [Asmaa] {
        var Names: [Asmaa] = [
            Asmaa(isFaved: false, id: 1, name: "ALLAH c.c.", arabic: "اللَّهُ", shortText: "Tüm isim ve sıfatları kendinde toplayan.", description:"ALLAH c.c. Gördüğümüz görmediğimiz, bildiğimiz bilmediğimiz bütün âlemlerin sâhibi ve mâliki, kâinatın yegâne yaratıcısı, her türlü övgüye ve ibâdete lâyık olan yüceler yücesi Rabbimizin doksan dokuz isminin bütün hususiyetlerini kendinde toplayan en kapsamlı özel adıdır."),
            
            Asmaa(isFaved: false, id: 2, name: "Er-Rahmân    ", arabic: "الرَّحْمَنُ", shortText: "Rahmetiyle muamele eden, esirgeyen.", description:"Er-Rahmân: Rahmet ve merhamet; acıma, bağışlama, kalp yufkalığı, şefkat ve ihsân anlamlarına gelir. “Rahmân” ve “Rahîm” isimleri, “çok şefkat ve merhamet eden” anlamındadır. Kur’ân’da “Rahmân” ismi elli yedi, “Rahîm” ismi yüz on beş defa Allah’a nisbet edilmektedir. “Rahmân”, Allah’ın zâtî ismi, “Rahîm” ise fiilî isimlerindendir. “Rahmân”, zâtî ismi olduğundan Allah’tan başkasına isim olarak verilemez. Fiilî isimlerinden olan “Rahîm” ise başkasına isim olarak verilebilir. Allah’ın bu ismi bir kulda tecelli ederse, o kul merhamet kanatlarını bütün yaratıklara açar. Allah’ın rahmeti bütün yaratılmışları kapsar. Rahmetiyle, inanan inanmayan bütün insanlara rızıklarını ve nimetlerini bol bol vermektedir.Hz. Peygamber Allah’ın rahmetini şöyle anlatır: “Şüphesiz Allah’ın yüz rahmeti vardır. Bunlardan bir tanesini yaratıklarına vermiştir. Yaratıkların birbirlerine acımaları bu rahmet sebebiyledir. Allah’ın rahmetinin doksan dokuzu kıyâmet günü içindir.”"),
            
            Asmaa(isFaved: false, id: 3, name: "Er-Rahim", arabic: "الرَّحِيمُ", shortText: "Merhamet eden, bağışlayan.", description:"El-Melik: Görülen ve görülmeyen bütün âlemlerin, bütün kâinatın tek sahibi ve mutlak surette tek hükümdârı demektir. Kendisine ibâdet edilmeye yegâne lâyık olan O’dur. O’nun istediği olur, istemediği olmaz. O, bir şeyin olmasını isterse, sadece “ol” der, o da derhal olur. Olmasını istemediği hiçbir şey de asla varlık sahasına çıkamaz. Bütün evren, yaratılmış olan her şey, mükemmel bir düzen içerisinde işlemektedir. Asla bir başı boşluk ve düzensizlik yoktur. Bütün idâre tek bir yerden geliyor. O Allah, dünya ve âhiret hayatındaki her şeye gerçek anlamda ve kayıtsız şartsız hâkim ve mâlik olan ve dilediği gibi tasarrufta bulunandır."),
            
            Asmaa(isFaved: false, id: 4, name: "El-Melik", arabic: "المَلِكُ", shortText: "Mülkün gerçek sahibi, mülk ve saltanatı devamlı olan.", description:"El-Melik: Görülen ve görülmeyen bütün âlemlerin, bütün kâinatın tek sahibi ve mutlak surette tek hükümdârı demektir. Kendisine ibâdet edilmeye yegâne lâyık olan O’dur. O’nun istediği olur, istemediği olmaz. O, bir şeyin olmasını isterse, sadece “ol” der, o da derhal olur. Olmasını istemediği hiçbir şey de asla varlık sahasına çıkamaz. Bütün evren, yaratılmış olan her şey, mükemmel bir düzen içerisinde işlemektedir. Asla bir başı boşluk ve düzensizlik yoktur. Bütün idâre tek bir yerden geliyor. O Allah, dünya ve âhiret hayatındaki her şeye gerçek anlamda ve kayıtsız şartsız hâkim ve mâlik olan ve dilediği gibi tasarrufta bulunandır."),
            
            Asmaa(isFaved: false, id: 5, name: "El-Kuddûs", arabic: "القُدُّوسُ", shortText: "Her türlü eksiklik ve ayıplardan münezzeh olan.", description:"El-Kuddûs: Hatadan, gafletten, âcizlikten, her türlü eksiklikten uzak, bütün kemâl sıfatları üzerinde toplamış, bütün övgülerin üstünde olan demektir. Her türlü ayıptan, kusurdan ve ihtiyaçtan uzak olan, her türlü hayır ve bereketin kaynağı olan mübarek zât demektir. Her türlü eksiklikten, lekeden, pastan, kirden son derece temiz demektir. Gördüğümüz görmediğimiz, bildiğimiz bilmediğimiz her şeyi yaratan Allah Teâlâ, kâinâtı akıllara durgunluk verecek bir düzen ile yaratmıştır."),
            
            Asmaa(isFaved: false, id: 6, name: "Es-Selâm", arabic: "السَّلَامُ", shortText: "Kullarını selâmete çıkaran.", description:"Es-Selâm: Her türlü eksiklikten, ayıptan, kusurdan, yaratılmışlara özgü değişim ve yok oluştan münezzeh ve sâlim olan; kullarını her türlü kötülüklerden, tehlikelerden selâmete çıkaran; Cennetteki kullarına selam veren demektir. Allah, gerek dünyada, gerekse âhirette tehlikeye düşen kullarını tehlikelerden kurtarıp selamete çıkarandır. Hz. Peygamber, her namazdan sonra; “Allah’ım! Sen’sin selâm ve Sen’dendir selâm!” buyurmuştur. Selâm, Esmâ-i Hüsnâ’dan biri olduğu için Müslüman olmayanlara bu lafızla selam verilmez. Müslüman olmayanlar, dua ve esenlik dileği olan “selâm”ı hak etmemişlerdir."),
            
            Asmaa(isFaved: false, id: 7, name: "El-Mü’min", arabic: "المُؤْمِنُ", shortText: "Gönüllerde iman ışığı uyandıran.", description:"El-Mü’min: Güven veren, va’dine güvenilen; inananları korku ve endişeden güvende kılan; mü’minlerin îmân ve samimiyetini tasdik eden; mûcizeler vermek suretiyle Peygamberlerinin doğruluğunu isbatlayan; kendisine sığınanları koruyan, emniyetle rahatlandıran demektir.Allah’ın kullarına en büyük nimetlerinden biri, îmândır. Diğeri, emniyettir. İnsan; canı, malı, ırzı, namusu için her zaman bir endişe ve korku içinde kalsaydı, bu ne büyük bir azap olurdu. Bu isim bir kulda tecellî edince, o kulun kalbine imân iyice yerleşir. O, güvenilir biri olur. Allah Teâlâ, mü’min isminin bir tecellisi olarak inananları korkulardan güvende kılıyor."),
            
            Asmaa(isFaved: false, id: 8, name: "El-Müheymin", arabic: "المُهَيْمِنُ", shortText: "Gözeten ve koruyan.", description:"El-Müheymin: Kâinatın bütün işlerini gözetleyip yöneten; bütün yaratıklarını gözetip koruyan; korkulardan emin kılan demektir. Yine kullarına asla zulmetmeyen; her söylediği ve yaptığına güvenilen; bütün kullarını hükmü altına alan; olup biten her şeyden haberdâr olan ve Peygamberi’ne indirdiği vahyin doğruluğuna tanıklık eden; kullarını dâimâ gözetim altında bulunduran; mü’minlere güven, sevgi ve huzur veren demektir."),
            
            Asmaa(isFaved: false, id: 9, name: "El-Aziz", arabic: "العَزِيزُ", shortText: "Mağlup edilmesi asla mümkün olmayan.", description:"El-Aziz: Yenilmesi mümkün olmayan gâlip; dengi ve benzeri bulunmayacak şekilde değerli ve şerefli; güçlü ve yenilmez demektir. Allah Teâlâ yegâne güç ve kuvvet sahibi olan mutlak gâliptir. O’nu âciz bırakacak hiç bir güç yoktur. Dilediğini izzetli, şerefli ve üstün kılar."),
            
            Asmaa(isFaved: false, id: 10, name: "El-Cebbâr", arabic: "الجَبَّارُ", shortText: "İstediğini mutlak yapan, dilediğine muktedir olan.", description:"El-Cebbâr: Dilediğini her durumda gerçekleştiren; istediğini zorla yaptırmaya muktedir olan; yaratılmışların halini iyileştiren; parçalanmış, dağılmış ve bozulmuş olanı düzeltip onaran; her şeyi tasarrufu altına alan demektir. Allah Teâlâ, kırılanları onarır, eksikleri tamamlar, her türlü perişanlıkları düzeltir, yoluna koyar. Düzeni bozulan her şeyi düzene koyar. Yaratıklarının ihtiyaçlarını giderir. Yaşama ve rızık sebeplerini sağlar. Kırılan ümitlerin canlanması, şaşırtıcı perişanlıkların iyi hale gelmesi ve yola konması için tek başvuru kaynağının Allah Teâlâ olduğunu bilmeli, yanlış yerlere başvurmamalıdır."),

            Asmaa(isFaved: false, id: 11, name: "El-Mütekebbir", arabic: "المُتَكَبِّرُ", shortText: "Her şeyde büyüklüğünü gösteren.", description: "El-Mütekebbir: Her zaman ve her yerde büyüklüğünü gösteren; zât ve sıfatlarının mâhiyeti bilinemeyecek kadar ulu, yaratılmışların sıfatlarından yüce olan; azgın ve zâlim insanları mutlak gücüne boyun eğmek zorunda bırakan demektir. Büyüklük ve yücelik, ancak Allah’a mahsustur. İnsan çalışıp çabalamalı büyük adam olmalı, ama asla büyüklenmemelidir. Yaratılmışlar içinde ilk defa kendini büyük gören İblis olmuş ve bu durum onun lanetlenmesine, cehenneme girmesine sebep olmuştur."),

            Asmaa(isFaved: false, id: 12, name: "El-Hâlık", arabic: "الخَالِقُ", shortText: "Her şeyi yoktan var eden.", description:"El-Hâlık: Her şeyi yaratan, yoktan var eden demektir. Allah Teâlâ, eşyayı, her hangi bir örneği ve benzeri olmadan yaratandır. Yarattığı her şeyi bütün ayrıntılarıyla bilir. Her şeyin varlığını, varlığı boyunca görüp geçireceği halleri bilir, olayları tayin ve tesbit eder, ona göre yaratır. Demek ki hâlık isminin iki anlamı vardır: birincisi; bir şeyin nasıl olacağını tayin ve tesbit etmek, ikincisi, o takdire uygun olarak o şeyi yaratmak, var etmek. Allah Teâlâ, her şeyi ezelde takdir etmiş, takdir ettiklerinin zamanı gelince bunları yaratmış, varlık sahasına çıkarmıştır. O’nun ilim, irâde, takdir ve yaratmasından hiç bir şey uzak kalamaz."),
            
            Asmaa(isFaved: false, id: 13, name: "El-Bârî", arabic: "البَارِىءُ", shortText: "Her şeyi uygun bir tarzda ve birbirine uygun yaratan.", description:"El-Bârî: Bir örneği ve maddesi olmaksızın yaratan; evrenin bütün parçalarını âhenkli ve düzenli olarak meydana getiren demektir. Allah Teâlâ, zât ve sıfatları bakımından yaratılmışlara asla benzemez. Yarattığı her şeyi hiç bir modele bağlı kalmaksızın yarattığı gibi, tam bir uygunluk ve kusursuzluk halinde yaratmıştır. Bir kulda bu isim tecellî edince, o kul yaptığı her şeyi adâletle, hakkâniyetle ve sağlam yapar."),
            
            Asmaa(isFaved: false, id: 14, name: "El-Musavvir", arabic: "المُصَوِّرُ", shortText: "Her şeye bir şekil ve hususiyet verip tasvir eden.", description:"El-Musavvir: Varlıkları çeşitli şekillerde yaratan; yarattığı her varlığa ayrı bir şekil ve husûsiyet veren demektir. Hâlik, bâri’ ve musavvir isimlerinin üçü de yaratıcı anlamındadır. Bunlardan hâlik; bir örneği, eşi, benzeri olmaksızın ilk defa yaratan demektir. Bâri’; yarattığı şeyi düzgün yaratan, yarattığı canlıları, organları yerli yerinde, uyumlu yaratan demektir. Musavvir de; yarattığı her şeye ayrı bir şekil, biçim ve husûsiyet veren demektir. Yeryüzünde bulunan milyarlarca insanın her bir organının bir diğerine benzemeyişi, Allah’ın yaratıcılığının mükemmelliğine delildir. Bu isimden nasip alan kullar, Allah’ın yarattığı her şeye hayranlıkla ve ibretle bakarlar"),
            
            Asmaa(isFaved: false, id: 15, name: "El-Gaffâr", arabic: "الغَفَّارُ", shortText: "Kullarının günahlarını örten, günahlarını bağışlayan.", description:"El-Gaffâr: Dâimâ affeden; kullarının günahlarını örten, ayıp ve kusurlarını bağışlayan; tekrarlanan günahları bağışlayan; mağfireti, bağışlaması sonsuz olan demektir. Mânevî kirlerden, günahlardan temizlenmek için Allah Teâlâ’ya istiğfar etmeli, mağfiret ve bağışlanma dilemeliyiz."),

            Asmaa(isFaved: false, id: 16, name: "El-Kahhâr", arabic: "القَهَّارُ", shortText: "Her şeye, her istediğini yapacak surette galip ve hakim olan.", description:"El-Kahhâr: Yenilmeyen, yegane gâlip demektir. Allah Teâlâ, her şeye, her istediğini yapacak şekilde gâlip ve hâkimdir. Kuvvet ve kudretiyle her şeyi içinden ve dışından kuşatmıştır. O’na karşı her şeyin boynu büküktür. Dilediğini istediği anda yok ve helak eder."),

            Asmaa(isFaved: false, id: 17, name: "El-Vehhâb", arabic: "الوَهَّابُ", shortText: "Çok fazla ihsan eden.", description:"El-Vehhâb: Karşılık beklemeden bol bol veren; hibesi ve lütfu çok olan demektir. Allah Teâlâ, bağışı çok olandır, karşılıksız verendir, nimetlerinin ardı arkası kesilmeyendir. İnanan inanmayan ayırımı yapmaksızın bütün kullarına nimetlerini bol bol verendir. Rahmeti gereği lütfu bol olan ve hayırlı işlerde başarıya ulaştırandır."),

            Asmaa(isFaved: false, id: 18, name: "Er-Rezzâk", arabic: "الرَّزَّاقُ", shortText: "Bütün mahlukatın rızkını veren ve ihtiyacını karşılayan.", description:"Er-Rezzâk: Bedenlerin ve ruhların gıdasını, bütün yaratıklarının rızkını yaratıp veren demektir. Allah Teâlâ, yarattığı bütün yaratıklarının rızkına kefildir. Yerde, gökte, yer altında, denizde vb. nerede canlı varsa hepsinin rızkını yaratan Allah Teâlâ’dır. Hepsinin rızkını tam vaktinde ve unutmadan verir. Ancak insanlara, yarattığı rızıkları meşrû yoldan arayıp bulmalarını emretmiştir. Bu isimden nasip alan kul, rızkın değil, Rezzâk’ın peşinden koşar. Her nimette O’nu hatırlar. Allah’ın cömertliğine hayran kalır."),

            Asmaa(isFaved: false, id: 19, name: "El-Fettâh", arabic: "الفَتَّاحُ", shortText: "Her türlü zorlukları kolaylaştıran, darlıktan kurtaran.", description:"El-Fettâh: İyilik kapılarını açan; hakemlik yapan; bütün anlaşmazlıklarda hakemlik yaparak mutlak adâleti gerçekleştiren; zulme uğrayanlara yardım eden; mü’min kullarını zafere ulaştıran; mü’minlere mânevî kapıları açıp kalplerden kederleri gideren; her derde çare bulan; her türlü engelleri kaldıran demektir. Allah Teâlâ, yürekten, tasaları, kederleri giderendir. İnsanı sıkıntılardan kurtarıp göğsüne genişlik verendir. Anlaşılması zor ilimlerin üzerindeki zorluğu gidererek anlaşılmasını kolaylaştırandır. Allah, insana hidâyet yollarını açar."),

            Asmaa(isFaved: false, id: 20, name: "El-Alîm", arabic: "العَلِيمُ", shortText: "Her şeyi en ince noktasına kadar bilen, ilmi ebedi ve ezeli olan.", description:"El-Alîm: Hakkıyla bilen demektir. Allah Teâlâ, zaman ve yer kaydı olmaksızın büyük küçük, gizli açık her şeyi bilendir. Olmuşu, olanı, olacağı en mükemmel bir şekilde bilir. Hiç bir şey O’nun bilgisi dışına çıkamaz. O’nun bilemeyeceği bir şey düşünmek mümkün değildir."),

            Asmaa(isFaved: false, id: 21, name: "El-Kâbıd", arabic: "القَابِضُ", shortText: "Dilediğine darlık veren, sıkan, daraltan.", description:"El-Kâbıd: Rızkı daraltan; canlıların ruhlarını alıp hayatlarına son veren demektir. Allah Teâlâ, istediğini sıkar, daraltır; istediğini genişletir. İstediğinden verdiği zenginliği, çoluk çocuğu, hayat zevkini, gönül ferahlığını alıverir. ihsânettiği şeyleri daraltır, azaltır. Güneşin doğmasıyla karanlığı giderir. Kuşlara gökyüzünde uçma imkânı verir, onları düşmekten korur. Bu ismi “Bâsıt” ismiyle beraber değerlendirmelidir."),

            Asmaa(isFaved: false, id: 22, name: "El-Bâsıt", arabic: "البَاسِطُ", shortText: "Dilediğine bolluk veren, açan, genişleten.", description:"El-Bâsıt: Rızkı genişleten; ruhları bedenlerine dağıtan demektir. Allah Teâlâ, kulunu darlıktan çıkaran, sıkıntıdan kurtarandır. İlâhî imtihanın gerçekleşmesi için bazan sıkar, bazan genişletir. Bazan darlık, sıkıntı verir. Bazan bolluk, rahatlık, huzur verir. Bu ismi, “Kâbıd” ismiyle beraber değerlendirmelidir."),

            Asmaa(isFaved: false, id: 23, name: "El-Hâfıd", arabic: "الخَافِضُ", shortText: "Yukarıdan aşağıya indiren, alçaltan.", description:"El-Hâfıd: Alçaltan; zillete düşüren; yukarıdan aşağıya indiren demektir. Allah Teâlâ, kâfirleri, zâlimleri, zorbaları alçaltır; mü’minleri, dostlarını yükseltir. İstediği kulunu yukarıdan aşağıya atıverir. En yüksek mertebelerden en aşağı mertebelere indiriverir. Allah’ın düşürdüğünü hiç kimse yükseltemez, yükselttiğini de hiç kimse alçaltamaz. Bu ismi “Râfi’” ismiyle beraber değerlendirmelidir."),
            
            Asmaa(isFaved: false, id: 24, name: "Er-Râfî", arabic: "الرَّافِعُ", shortText: "Yukarı kaldıran, yükselten.", description:"Er-Râfî: Yücelten, yükselten, yukarı kaldıran, şeref veren demektir. Allah Teâlâ, dilediği kuluna şeref bahşederek yükseltir, diğer kullarından üstün kılar. Dilediğini zengin kılar, şerefli kılar, saygıdeğer kılar. Dilediğine îmân bahşeder, sâlih ameller işlemesine ve cennetine girmesine imkân verir. Bu ismi, “Hâfid” ismiyle beraber değerlendirmelidir. Râfi’; dostlarının tâat ve amellerini kabul edip kendisine yaklaştıran, dünyada şerefli kılan demektir. Hâfid de; kendisine itâat etmeyenleri kendisinden uzaklaştıran, mertebelerini düşüren demektir."),
            
            Asmaa(isFaved: false, id: 25, name: "El-Muiz", arabic: "المُعِزُّ", shortText: "İzzet verip ağırlayan.", description:"El-Muiz: Üstün kılan, izzet ve şeref veren; mülkü dilediğine veren demektir. Allah Teâlâ, kendisine inananları yükseltir, şereflendirir, başkalarına üstün kılar. Îmân ehli, Allah’ın azîz ve değerli kıldığı kimselerdir. “Muizz” ismini “Müzill” ismi ile beraber değerlendirmelidir."),
            
            Asmaa(isFaved: false, id: 26, name: "El-Muzil", arabic: "المُذِلُّ", shortText: "Zillete düşüren, hor ve hakir eden.", description:"El-Muzil: Zillete düşüren, hor ve hakir kılan, rezil ve perişan eden, alçaltan demektir. Gönülleri dünya hırsı ile yanıp tutuşan kişiler, Allah’ın zelil kıldıklarıdır. Bunların şiarı dünya çıkarı için nefsini alçaltmaktır. Bunlar yarın Allah’ın huzuruna yüzleri kararmış olarak çıkacaklardır. “Müzill” ismini, “Muizz” ismi ile beraber değerlendirmelidir."),

            Asmaa(isFaved: false, id: 27, name: "Es-Semî", arabic: "السَّمِيعُ", shortText: "Her şeyi işiten.", description:"Es-Semî: Sonsuz işiten, her türlü kısıtlamadan yüce olarak gizli açık her şeyi işiten; işitilecek şeyler kendisine gizli kalmayan; dilek, dua ve yakarışları kabul eden demektir. Allah Teâlâ, ister açık, ister gizli bütün sesleri, fısıltıları işitir. Kendisine içinden hamd edenin hamdini işiterek onu mükâfâtlandırır. Dua edenlerin dualarını kabul eder. Allah’ın işitmesi kullarınki gibi kulak ve ses gibi bazı vasıtalarla değildir."),

            Asmaa(isFaved: false, id: 28, name: "El-Basîr", arabic: "البَصِيرُ", shortText: "Her şeyi gören.", description:"El-Basîr: Sonsuz görücü; her şeyi gören, bilen; kendisinden hiç bir şey saklanamayan demektir. Allah Teâlâ’nın görmesi de işitmesi ve diğer isim ve sıfatları gibi sonsuzdur. Her hangi bir organ ve vasıta ile değildir. Görme konusu olan her şeyi görür. Açıkta olanları gördüğü gibi gizli olanları da görür. Dışımızı gördüğü gibi içimizi de görür. O hâlde devamlı bir şekilde Rabbimiz tarafından görüldüğümüzü ve gözetlendiğimizi unutmamamız, buna göre söz ve davranışlarımıza dikkat etmemiz gerekir."),

            Asmaa(isFaved: false, id: 29, name: "El-Hakem", arabic: "الحَكَمُ", shortText: "Her işte hikmet ve adaletle hükmeden.", description:"El-Hakem: Hükmeden, hakkı yerine getiren; hüküm yetkisi kendisine ait olan; son hükmü verecek olan demektir. Allah Teâlâ, hâkimdir. Her şeyin hükmünü O verir. Verdiği hükmü tamamiyle yerine getirir. O’nun hükmünü engelleyecek, bozacak, değiştirecek, geri bıraktıracak hiç kimse yoktur. Kıyâmet gününde Allah Teâlâ hükmünü verecek, adâlet tam olarak gerçekleşecek ve herkes hak ettiğinin karşılığını tam olarak alacaktır. Hiç kimseye en küçük bir haksızlık yapılmayacaktır."),

            Asmaa(isFaved: false, id: 30, name: "El-Adl", arabic: "العَدْلُ", shortText: "Son derece adaletli olan.", description:"El-Adl: Mutlak adâlet sahibi, çok adâletli, asla zulmetmeyen; her şeyi yerli yerine koyan demektir. Allah Teâlâ, çok adâletlidir. Hiç kimseye en küçük bir haksızlık yapmaz. Herkes neyi hak ettiyse, herkese hakkını tam olarak verir. Yaptığı her şey, akla, mantığa, hikmet ve maslahata uygundur. Bu isimden nasip alan kul, zulmün her çeşidinden kaçınır; kendi aleyhine bile olsa adâletten ayrılmaz."),

            Asmaa(isFaved: false, id: 31, name: "El-Latîf", arabic: "اللَّطِيفُ", shortText: "İşlerin bütün inceliklerini bilen.", description:"El-Latîf: Yaratılmışların ihtiyaçlarını en ince ayrıntıya varıncaya kadar bilip sezilmez yollarla karşılayan; kullarına yumuşaklıkla, lütuf ve ihsânıyla muâmele eden demektir. Allah Teâlâ, kullarına iyilik ve merhamet edendir. Fiillerini yumuşaklıkla gerçekleştirendir. Sonsuz lütuf ve kerem sahibidir. Kendisine gizli olan hiç bir şey yoktur."),

            Asmaa(isFaved: false, id: 32, name: "El-Habîr", arabic: "الخَبِيرُ", shortText: "Her şeyin iç yüzünden, gizli tarafından haberdar olan.", description:"El-Habîr: Her şeyi bilen, her şeyin iç yüzünden, gizli taraflarından haberdâr olan demektir. Allah Teâlâ, yerde ve gökte, bütün evrende olan gizli açık her şeyden haberdârdır. O’nun bilemeyeceği bir şey düşünmek mümkün değildir. Bu bakımdan yaptığımız her şeyi Allah’ın bildiğini düşünerek yapmalıyız."),
            
            Asmaa(isFaved: false, id: 33, name: "El-Halîm", arabic: "الحَلِيمُ", shortText: "Yumuşak davranan, hilmi çok olan.", description:"El-Halîm: Suçluların cezasını vermeye gücü yettiği hâlde cezalandırmayıp onlar hakkında yumuşak davranan, cezalarını geriye bırakan; acele ve kızgınlıkla muâmele etmeyen demektir. Allah Teâlâ, günahları yüzünden kullarına olan lütuf ve ihsânını esirgemez. İyi olsun kötü olsun bütün kullarını rızıklandırır; belâ ve âfetlerden korur. Acelecilikle ve kızgınlıkla davranmaz. Çok yumuşak davranır. Ceza vermekte acele etmez. Süre tanır, ama ihmal etmez."),
            
            Asmaa(isFaved: false, id: 34, name: "El-Azîm", arabic: "العَظِيمُ", shortText: "Pek azametli ve büyük olan.", description:"El-Azîm: Büyük, yüce, ulu demektir. Allah Teâlâ, zât ve sıfatları bakımından en büyüktür. Mutlak ve ekmel büyüklük Allah’a mahsustur. O, hiç bir şekilde âciz bırakılmayacak olan Kâdir-i mutlaktır. Akıl, O’nun büyüklüğünü idrâkten âcizdir."),
            
            Asmaa(isFaved: false, id: 35, name: "El-Gafûr", arabic: "الغَفُورُ", shortText: "Çok bağışlayan, magfireti çok olan.", description:"El-Gafûr: Günahları bağışlayan; affeden demektir. Allah Teâlâ, bağışlaması bol olandır. Kulun günahı ne kadar çok olursa olsun Allah Teâlâ, bunları meydana çıkarıp kulunu rezil ve rüsvay etmez, bunları örter ve gizler. Kulun, işlediği gü nahları ve suçları bağışlar. Sonsuz mağfiret edici ve bağışlayıcıdır. Bu isimden nasip alan kul, daima istiğfâra yönelir. Şahsına yapılan haksızlıkları bağışlar. Kin tutmaz."),
            
            Asmaa(isFaved: false, id: 36, name: "Eş-Şekûr", arabic: "الشَّكُورُ", shortText: "Kendi rızası için yapılan iyi işleri, ziyadesiyle mükafatlandıran.", description:"Eş-Şekûr: Az iyiliğe çok mükâfât veren; kendi rızası için yapılan iyilikleri fazlasıyla mükâfâtlandıran demektir. Allah Teâlâ, kulların işlediği ibâdet ve iyilikleri fazlasıyla karşılayandır. Kul, Allah’ın verdiği nimetlere şükürle karşılık vermelidir. Kul şükrederse, Allah onun şükrünü karşılıksız bırakmaz, fazlasıyla mükâfâtlandırır."),
            
            Asmaa(isFaved: false, id: 37, name: "El-Aliyy", arabic: "العَلِيُّ", shortText: "Çok yüce. Pek yüksek olan.", description:"El-Aliyy: Pek yüce, pek yüksek demektir. Allah Teâlâ, insan tasavvurunun tahayyül edeceği her şeyden daha büyük, daha yüce ve daha yüksektir. İzzet, şeref ve hükümranlık bakımından O’ndan daha yüce bir varlık yoktur. O’nun yüksekliği cisimlerin sahip olduğu türden değildir. Yücelik ve üstünlük bakımındandır."),
            
            Asmaa(isFaved: false, id: 38, name: "El-Kebîr", arabic: "الكَبِيرُ", shortText: "Büyüklüğünde hudut olmayan.", description:"El-Kebîr: Büyük ve ulu demektir. Allah Teâlâ, her hususta insanların kavrayamayacağı kadar ulu ve büyüktür. Zâtının ve sıfatlarının mâhiyeti bilinemeyecek kadar uludur. Mutlak büyüktür. Kudret ve hükümranlığı sınırsızdır. Hiç bir şeye muhtaç değildir. Yaratılmışlara benzemez. O’nun büyüklüğü, mekâna bağlı bir büyüklük değildir. O, bundan münezzehtir."),
            
            Asmaa(isFaved: false, id: 39, name: "El-Hafîz", arabic: "الحَفِيظُ", shortText: "Yapılan işleri bütün tafsilatıyla, ayrıntılarıyla tutan.", description:"El-Hafîz: Koruyup gözeten; kendisinden gizli hiç bir şey olmayan demektir. Allah Teâlâ, evrenin düzenini koruyup sürdürendir. Her şeyi eksiksiz kaydedip hesaba çekmek üzere koruyandır. İnsanların niyetlerini ve bütün sırlarını bilendir. İnsanların söz ve hareketlerini melekler aracılığıyla tesbit ve tescil ettirendir. Dostlarını kötülüklerden koruyandır."),
            
            Asmaa(isFaved: false, id: 40, name: "El-Mukît", arabic: "المُقِيتُ", shortText: "Yaratılmış her şeyin azığını veren.", description:"El-Mukît: Yaratılmışların her türlü gıdalarını yaratıp veren; her şeye gücü yeten ve koruyan demektir. Allah Teâlâ, bedenlerin ve ruhların gıdasını yaratıp verendir. Yarattığı bütün canlılara ne kadar ömür takdir etmişse ona göre rızıklarını da tayin ve takdir etmiştir. Herkesin rızkı bellidir. Herkes kendi rızkını yer, kimse kimsenin rızkını yemez."),
            
            Asmaa(isFaved: false, id: 41, name: "El-Hasîb", arabic: "الحَسِيبُ", shortText: "Herkesin hayatı boyunca yaptıklarının hesabını soran.", description:"El-Hasîb: Kullarına yeten; onları hesaba çeken demektir. Allah Teâlâ, herkesin hayatı boyunca yapıp ettiklerinin bütün ayrıntılarıyla hesabını iyi bilendir. Bütün kullarını yaptıklarından dolayı veya yapmaları gerekenleri yapmadıklarından dolayı çok ayrıntılı bir şekilde hesaba çekecek ve herkesin hak ettiğini tam olarak verecektir."),
            
            Asmaa(isFaved: false, id: 42, name: "El-Celîl", arabic: "الجَلِيلُ", shortText: "Azamet sahibi olan, ululuk sahibi olan.", description:"El-Celîl: Azamet ve ululuk sahibi demektir. Allah Teâlâ, bütün sınırlama ve benzerlikleri aşan bir yüceliğe sahiptir. Değer ve mertebece en yüce olandır. Mü’minleri yücelten, amellerini kabul edip mükâfâtlarını artırandır. O, zât, sıfat ve fiilleri itibariyle en büyüktür. O’nun büyüklüğü hacim itibariyle değildir; şân, şeref ve yücelik itibariyledir."),

            Asmaa(isFaved: false, id: 43, name: "El-Kerîm", arabic: "الكَرِيمُ", shortText: "Çok ikram edici. Keremi ve mağfireti bol olan.", description:"El-Kerîm: İhsânı, in’âmı, lütfu, keremi bol olan, sonsuz cömert demektir. Allah Teâlâ, her türlü faziletin sahibidir. Hiç bir karşılık beklemeden verendir. Yardımı ve ikrâmı sonsuz ve sınırsızdır. Muktedirken, affedendir. Va’dini yerine getirendir. Kendisine sığınanı yüz üstü bırakmayandır. Az da olsa işlenen iyi ameli kabul eden, karşılığını fazlasıyla verendir. Bu isimden nasip alan kul, cimriliğin her çeşidinden kurtulur. Allah’ın kendisine verdiği nimetleri diğer kullarıyla paylaşmasını bilir. Şahsiyetini zedeleyecek her türlü rezillikten kurtulur."),

            Asmaa(isFaved: false, id: 44, name: "Er-Rakîb", arabic: "الرَّقِيبُ", shortText: "Bütün varlıklar üzerine gözcü olan", description:"Er-Rakîb: Her şeyi gözetleyip denetleyen; kontrol eden demektir. Allah Teâlâ, yaratıklarından bir an bile gâfil değildir. Kim ne yaparsa onu görür ve bilir. Hiçbir şey Allah’tan gizli kalmaz. Bütün varlıklar üzerinde gözcüdür, gözetleyicidir. Bütün işler O’nun denetimi ve gözetimi altında meydana gelmektedir. O, bütün olan bitenlere şahittir. Herkese yaptığının karşılığını verir."),

            Asmaa(isFaved: false, id: 45, name: "El-Mücîb", arabic: "المُجِيبُ", shortText: "Dua edenlerin dualarını kabul eden, isteklerini veren.", description:"El-Mücîb: Kendine yalvaranların isteklerini veren; kullarının dileklerine ve dualarına karşılık veren demektir. Allah Teâlâ, kullarına, onlardan daha yakındır. Kendine yalvaranları işitir, bilir ve onların isteklerini verir. İnsanın duâya şiddetle ihtiyacı vardır. Duâ, bir bakıma ibâdettir. Duâdan mahrum kalmamak lazımdır."),

            Asmaa(isFaved: false, id: 46, name: "El-Vâsî", arabic: "الوَاسِعُ", shortText: "Lütfu bol olan.", description:"El-Vâsî: İlmi ve merhameti her şeyi kuşatan demektir. Allah Teâlâ, kullarına bolca ihsân eden, rızıklarını genişletendir. Allah ilim, lütuf ve ihsânı ile her şeyi kuşatmıştır. Nimetlerinin bir kısmı fayda sağlayan türden, diğer bir kısmı da zararları gideren türdendir."),

            Asmaa(isFaved: false, id: 47, name: "El-Hakîm", arabic: "الحَكِيمُ", shortText: "Emirleri, kelamı ve bütün işleri hikmetli olan.", description:"El-Hakîm: Hikmet sahibi demektir. Allah Teâlâ, yaptığı her şeyi yerli yerince, eksiksiz ve tam yapar. En üstün bir ilim sahibidir ve yaptığı her şey mutlaka bir hikmete mebnîdir; hikmetsiz asla iş yapmaz. Bütün emirleri insanların yararına olduğu gibi bütün yasakları da insanların zararınadır."),

            Asmaa(isFaved: false, id: 48, name: "El-Vedûd", arabic: "الوَدُودُ", shortText: "İyi kullarını seven, sevilmeye ve dostluğa hakkıyla layık olan.", description:"El-Vedûd: Çok seven ve çok sevilen; sevilmeye lâyık olan demektir. Allah Teâlâ, sâlih kullarını sever, sâlih kulları da Allah’ı sever. Sâlih kullarından râzıdır. Allah yaratılmış bütün varlıkların hayrını ister. Bu nedenle onlara ihsân ve ikrâmlarda bulunur. Sevilmeye en çok lâyık olan da O’dur. Her mü’minin hedefi Allah dostluğunu kazanabilmek olmalıdır. Bunun için her türlü fedakârlığa katlanmalıdır. Bu isimden nasip alan kul, hem Allah adına herkesi, her şeyi sever; hem de herkes tarafından sevilir."),

            Asmaa(isFaved: false, id: 49, name: "El-Mecîd", arabic: "المَجِيدُ", shortText: "Şanı çok büyük ve çok yüksek olan.", description:"El-Mecîd: Şânı büyük, yüksek; lütuf ve ikrâmı bol demektir. Allah Teâlâ, her türlü eksikliklerden yücedir. Şânı büyüktür. Lütuf ve keremi çoktur. Her türlü övgüye lâyıktır. Affı, ihsânı, rahmeti ve yardımı sonsuzdur. Nimetleri saymakla bitmez."),

            Asmaa(isFaved: false, id: 50, name: "El-Bâis", arabic: "البَاعِثُ", shortText: "Ölüleri diriltip kabirlerinden çıkaran.", description:"El-Bâis: Ölüleri dirilten, Peygamber gönderen demektir. Allah Teâlâ, öldükten sonra diriltendir. İnsanlar ölüp toprak olduktan sonra onları diriltecek, kabirlerinden çıkaracak, mahşerde toplayacak, çok ayrıntılı bir şekilde hesaba çekecektir. Allah Teâlâ, aynı zamanda insanlara doğru yolu göstermek üzere Peygamberler gönderendir. Peygamberlere uyanlar kurtulacak, uymayanlar azâbı hak edeceklerdir."),

            Asmaa(isFaved: false, id: 51, name: "Eş-Şehîd", arabic: "الشَّهِيدُ", shortText: "Her zaman ve her yerde hazır ve nazır olan.", description:"Eş-Şehîd: Her zaman, her yerde hazır olan; her şeye şâhit olan; kendisine hiçbir şey gizli olmayan demektir. Allah Teâlâ, her şeyi bilendir. İlminden hiç bir şey gizli olmayandır. Allah, açıkta olanları da bilir, gizli olanları da bilir. O, her şeye şâhittir. Âhirette herkese halini bildirecektir."),

            Asmaa(isFaved: false, id: 52, name: "El-Hakk", arabic: "الحَقُّ", shortText: "Vacib'ul vücut olan, varlığı hiç değişmeden duran.", description:"El-Hakk: Varlığı gerçek olan, varlığı hiç değişmeden duran; varlığı ve ilâhlığı kesin olan, hükmünün gereğini yerine getiren demektir. Allah Teâlâ, varlığı ve ilâhlığı kesin olan, inkârı mümkün olmayandır. O’nun zâtı yokluğu kabul etmediği gibi bir değişikliği de kabul etmez. Hükmünün gereğini yerine getirendir. Ezelî ve ebedî olandır. Değişmeksizin varlığı devam edendir. Varlığı fiilen gerçek olandır yani sadece zihinde değil, zihnin dışında da var olandır."),

            Asmaa(isFaved: false, id: 53, name: "El-Vekîl", arabic: "الوَكِيلُ", shortText: "İşlerini kendisine bırakanların işini düzelten ve her şeyin iyisini temin eden.", description:"El-Vekîl: İşlerini kendisine bırakanların işlerini en mükemmel bir şekilde yapan; kendisine güvenilip dayanılan demektir. Allah Teâlâ, her bakımdan insanın güvenip dayanacağı varlıktır. En güzel vekildir, en büyük vekildir. Yarattığı bütün varlıkların işlerini idare edendir. Allah Teâlâ, elinden geleni yaptıktan sonra işini Allah’a havale edeni, mükâfâtlandırır."),

            Asmaa(isFaved: false, id: 54, name: "El-Kaviyy", arabic: "القَوِيُّ", shortText: "Pek kuvvetli. Pek güçlü olan.", description:"El-Kaviyy: Pek güçlü; gücü her şeye yeten demektir. Allah Teâlâ, tam bir kudret sahibidir. Gücü, kuvveti sonsuzdur; bitmez, tükenmez. Bir sınıra sığmaz, ölçüye gelmez. Nicelik ve nitelik bakımından üstün kudrete sahiptir. Gücünün yetmeyeceği bir şey düşünülemez. O, her şeyi etkiler, ama hiç bir şey O’nu etkileyemez."),

            Asmaa(isFaved: false, id: 55, name: "El-Metîn", arabic: "المَتِينُ", shortText: "Çok sağlam olan.", description:"El-Metîn: Sonsuz kudrete sahip; son derece güçlü, kuvvetli; dayanıklı, sağlam demektir. Allah Teâlâ, sonsuz bir güce sahiptir. Fiillerinden dolayı zatına her hangi bir zorluk ve yorgunluk ilişmez. Kuvveti azalıp gevşemez. Hiçbir şey O’nu âciz bırakamaz. Hiç kimsenin yardımına da muhtaç değildir. Allah’ın “Kaviyy” ismi, kudretinin kemâlini ifâde eder. Bütün nesne ve olayları etkileyendir. “Metîn” ismi, kuvvetinin şiddetini bildirir. Dıştan gelebilecek hiç bir etkiyi kabul etmeyendir."),

            Asmaa(isFaved: false, id: 56, name: "El-Veliyy", arabic: "الوَلِيُّ", shortText: "İyi kullarına, gerçek mü’minlere dost olan.", description:"El-Veliyy: Dost ve yardımcı demektir. Allah Teâlâ, sevdiği kullarının dostudur. Onlara yardım eder; sıkıntılarını, darlıklarını giderir; ferahlık verir. Dünya ve âhiret işlerinde başarıya ulaştırır. Mü’minlerin yardımcısı ve koruyucusudur. Allah’tan başka gerçek dost ve yardımcı yoktur."),

            Asmaa(isFaved: false, id: 57, name: "El-Hamîd", arabic: "الحَمِيدُ", shortText: "Her türlü hamd ve övgüye layık olan.", description:"El-Hamîd: Övülmeye lâyık olan demektir. Allah Teâlâ, bütün isimleri, sıfatları ve fiilleriyle övülmeye tek lâyık olan zâttır. Bütün varlığın diliyle övülen ve şükredilendir. Allah Teâlâ, bizâtihî övülmeye lâyık olandır. Aynı zamanda insanların işledikleri iyi fiiller sebebiyle onları över ve mükâfâtlandırır."),

            Asmaa(isFaved: false, id: 58, name: "El-Muhsî", arabic: "المُحْصِي", shortText: "İstisnasız her şeyin tek tek sayısını bilen.", description:"El-Muhsî: Sonsuz ilmiyle her şeyin sayısını bilen, her yapılanı bir bir sayan demektir. Allah Teâlâ, sonsuz ilmi ile her şeyi kuşatmıştır. Her şeyi tek tek ve bütün ayrıntılarıyla bilendir. O’nun ilminden hiç bir şey hariç kalamaz. Bütün amellerin sayısını bilir, kıyâmet günü bunların hepsinin karşılığını verir. Hiç birini unutmaz ve atlamaz."),

            Asmaa(isFaved: false, id: 59, name: "El-Mübdi", arabic: "المُبْدِىءُ", shortText: "Bütün mahlukatı maddesiz ve örneksiz olarak ilk baştan yaratan.", description:"El-Mübdi: Yaratıkları maddesiz ve örneksiz olarak ilk baştan yaratan demektir. Allah Teâlâ, kâinâtı yaratırken daha önce bir benzeri ve örneği olmaksızın yaratmıştır. İşte esas yaratma denilen, ilk maddesi, örneği olmaksızın yaratmadır. Bu, yoktan var etmedir ve Allah’a mahsustur."),

            Asmaa(isFaved: false, id: 60, name: "El-Muid", arabic: "المُعِيدُ", shortText: "Yaratılmışları yok ettikten sonra tekrar yaratan.", description:"El-Muid: Yaratılmışları öldürdükten, yok ettikten sonra tekrar yaratan; öldükten sonra dirilten demektir. Allah Teâlâ, ilk defa yarattığı bütün insanları öldürecek, sonra tekrar diriltecek ve dünya hayatlarındaki inanç ve amellerinden hesaba çekecektir. Hayat, sadece dünya hayatından ibaret değildir. Tekrar bir hayat vardır ki gerçek ve devamlı hayat budur. İnsanlar buna göre hareket etmelidir."),
            
            Asmaa(isFaved: false, id: 61, name: "El-Muhyî", arabic: "المُحْيِي", shortText: "İhya eden, dirilten, can bağışlayan, sağlık veren.", description:"El-Muhyî: Can veren, yaşatan demektir. Allah Teâlâ, can bağışlayan, sağlık verendir. Ölüleri diriltendir. Ölü beldeleri gökten indirdiği su ile canlandıran, yeryüzünü bitkilerle donatandır. İlk olarak yaratan, can veren Allah, öldükten sonra tekrar hayat vermeye kâdirdir. Ölü kalpleri ilâhî hidâyet ve marifetle canlandırandır."),
            
            Asmaa(isFaved: false, id: 62, name: "El-Mümît", arabic: "المُمِيتُ", shortText: "Ölümü yaratan, öldüren.", description:"El-Mümît: Öldüren, canlının hayatına son veren demektir. Allah Teâlâ, canlılara hayat verdiği gibi, ezelî ilmindeki takdire göre vakti gelince bu hayatlara son verendir. Fânî hayat, doğumla başlar, ölümle biter. Hayat dediğimiz ruhla cesedin birleşmesidir. Ölüm ise ruhun cesedden ayrılmasıdır. Ruh, ölmez. Başka bir hayatla devam eder. Kul için, ölüm sonrası başlayacak yeni ve devamlı hayata iyi hazırlık yapmak mühimdir."),
            
            Asmaa(isFaved: false, id: 63, name: "El-Hayy", arabic: "الحَيُّ", shortText: "Diri, tam ve mükemmel manasıyla hayat sahibi.", description:"El-Hayy: Diri, canlı olan; ölmek şânından olmayan demektir. Allah Teâlâ, bütün hayatların kaynağıdır. Hep diridir. Allah’ın hayy (diri) oluşu, yaratılmış varlıklarda olduğu gibi organik bir canlılık değildir. Hiç bir şeyden gâfil olmayan, hata yapmayan, kâinâtta kendisinden hiç bir şey gizli olmayan demektir."),

            Asmaa(isFaved: false, id: 64, name: "El-Kayyûm", arabic: "القَيُّومُ", shortText: "Gökleri, yeri ve her şeyi tutan.", description:"El-Kayyûm: Olup kimseye muhtaç değildir. Ezelî ve ebedîdir. Her şeyin varlık kazanması ve varlığını devam ettirmesi ancak Allah’ın yaratması, maddî mânevî ihtiyaçlarını gidermesi ve korumasıyla mümkündür. Yeri, gökleri ayakta tutan O’dur."),

            Asmaa(isFaved: false, id: 65, name: "El-Vâcid", arabic: "الوَاجِدُ", shortText: "İstediğini, istediği vakit bulan.", description:"El-Vâhid: Bir olan, tek olan; zâtında, sıfatlarında, isimlerinde ve fiillerinde asla ortağı, dengi ve benzeri bulunmayan demektir. Allah Teâlâ, tektir, bölünüp parçalara ayrılmaz. Benzeri yoktur. Allah’ın bir olması sayı bakımından değildir, büyüklük ve yücelik açısındandır. O, bölünmesi ve artması mümkün olmayan tek bir varlıktır."),

            Asmaa(isFaved: false, id: 66, name: "El-Mâcid", arabic: "المَاجِدُ", shortText: "Kadri büyük, keremi bol olan.", description:"El-Mâcid: Şânı ve kadri büyük; kerem ve cömertliği bol demektir. Allah Teâlâ, yardımı, ihsânı bol olandır. O’nun kullarına olan kerem ve cömertliği ifâdeye sığmaz, ölçüye gelmez. Bir taraftan kullarını iyi işler yapmaya muvaffak kılar; öbür taraftan onları güzel sıfatlara sahip olduklarından över."),

            Asmaa(isFaved: false, id: 67, name: "El-Vâhid", arabic: "الوَاحِدُ", shortText: "Tek olan.", description:"El-Vâhid: Bir olan, tek olan; zâtında, sıfatlarında, isimlerinde ve fiillerinde asla ortağı, dengi ve benzeri bulunmayan demektir. Allah Teâlâ, tektir, bölünüp parçalara ayrılmaz. Benzeri yoktur. Allah’ın bir olması sayı bakımından değildir, büyüklük ve yücelik açısındandır. O, bölünmesi ve artması mümkün olmayan tek bir varlıktır."),

            Asmaa(isFaved: false, id: 68, name: "Es-Samed", arabic: "الصَّمَدُ", shortText: "Sığınacak tek dayanak olan.", description:"Es-Samed: Her şeyin kendisine muhtaç olduğu, kendisinin hiç bir şeye muhtaç olmadığı; ihtiyaçların giderilmesi ve ızdırapların dindirilmesi için başvurulacak tek merci demektir. Allah Teâlâ, yaratıkların her türlü ihtiyaçlarını gidermek için başvurdukları tek başvuru kaynağıdır. Her türlü yaratığın her türlü ihtiyacını en mükemmel bir şekilde karşılar ve giderir. Kendisi ise hiç bir şeye muhtaç değildir."),

            Asmaa(isFaved: false, id: 69, name: "El-Kâdir", arabic: "القَادِرُ", shortText: "Her şeye gücü yeten, her istediğini yapmaya kâdir olan.", description:"El-Kâdir: Her şeye gücü yeten; kudret sahibi demektir. Allah Teâlâ, istediğini, istediği gibi yapmaya gücü yetendir. Her şeyi takdir eden, planlı ve ölçülü yapandır. Hiçbir şey O’nu âciz bırakamaz. Âlem, mutlak irâde ve kudrete sahip olan Allah tarafından yaratılmıştır."),

            Asmaa(isFaved: false, id: 70, name: "El-Muktedir", arabic: "المُقْتَدِرُ", shortText: "Kuvvet ve kudret sahipleri üzerinde dilediği gibi tasarruf eden.", description:"El-Muktedir: Tam bir kudret sahibi; her şeye gücü yeten demektir. Allah Teâlâ, kuvvet ve kudret sahipleri üzerinde istediği gibi tasarruf edendir. O’nun “Kâdir” oluşu, istediğini, istediği anda ve istediği şekilde yaratma gücüne sahip olması demektir. “Muktedir” olması ise, bilfiil gücünü yarattıklarında göstermesidir."),

            Asmaa(isFaved: false, id: 71, name: "El-Mukaddim", arabic: "المُقَدِّمُ", shortText: "İstediğini ileri geçirip, öne alan.", description:"El-Mukaddim: İstediğini öne alan, ileri geçiren demektir. Allah Teâlâ, dilediği şeyi veya kimseyi öne alan, önde bulundurandır. Allah’ın daveti geneldir. Fakat hidâyet ettikleri davete uyar, ileri gider. Hidâyet etmedikleri geri kalır. Allah’ın emir ve yasakları bütün kullar içindir. Fakat Allah’ın muvaffak ettikleri bunlara uyar, yükselir; muvaffak etmedikleri geride kalır. O hâlde hem akıl ve irâdemizi Allah’a îmân ve itâat yönünde kullanmalı, hem de Allah’tan hidâyet istemelidir. “Mukaddim” ismi, “Muahhir” ismiyle beraber değerlendirilmelidir."),

            Asmaa(isFaved: false, id: 72, name: "El-Muahhir", arabic: "المُؤَخِّرُ", shortText: "İstediğini geri koyan, arkaya bırakan.", description:"El-Muahhir: İstediğini geri koyan, arkaya bırakan demektir. Allah Teâlâ, hikmeti gereği geri bırakılması gerekenleri geri bırakır. “Mukaddim” ismi ile ilgili açıklamalarımız “Muahhir” ismi ile de ilgilidir. Esasen bu iki isim beraber değerlendirilmelidir. Bazan Allah Teâlâ, kulların istediklerini bir hikmeti gereği geri bırakır. İmtihan dünyasında olduğumuzu unutmamamız gerekir."),

            Asmaa(isFaved: false, id: 73, name: "El-Evvel", arabic: "الأَوَّلُ", shortText: "Başlangıcı olmayan, ilk olan.", description:"El-Evvel: İlk; varlığının başlangıcı olmayan demektir. Allah Teâlâ, bütün varlıklardan öncedir. Varlığının bir evveli, başlangıcı yoktur. O, kadîmdir, ezelîdir. Varlığı kendi zâtıyladır. Bütün varlıklar varlığını O’ndan almaktadır. Yaratmayı başlatan O’dur. “Evvel” ismini “Âhir” ismiyle beraber değerlendirmelidir."),

            Asmaa(isFaved: false, id: 74, name: "El-Âhir", arabic: "الآخِرُ", shortText: "Bitişi olmayan, son olan.", description:"El-Âhir: Varlığının sonu olmayan demektir. Allah Teâlâ, varlığı devamlı olandır. Varlığının başlangıcı olmadığı gibi sonu da yoktur. Allah, eşyanın evveli olması bakımından “Evvel”dir. Eşyanın sonu Allah’tan olması bakımından da “Âhir”dir. “Âhir” ismini, “Evvel” ismiyle beraber değerlendirmelidir."),

            Asmaa(isFaved: false, id: 75, name: "Ez-Zâhir", arabic: "الظَّاهِرُ", shortText: "Açıkca bilinen, âşikâr olan.", description:"Ez-Zâhir: Varlığı apaçık demektir. Allah Teâlâ, varlığını ve birliğini belgeleyen birçok delil bulunması açısından aşikârdır. Her şeyin üstünde olan, her şeyden yüce olandır. Allah’ın varlığı o kadar açıktır ki insanın gördüğü her şey, ibret nazarıyla baktığı takdirde onu, Allah’a götürür. “Zâhir” ismi, “Bâtın” ismiyle beraber değerlendirilmelidir."),

            Asmaa(isFaved: false, id: 76, name: "El-Bâtın", arabic: "البَاطِنُ", shortText: "Gizli olan.", description:"El-Bâtın: Zâtının görülmesi ve mâhiyetinin bilinmesi açısından gizli demektir. Allah Teâlâ, gizlidir. Çünkü O, gözle görülemez, künhüyle bilinemez. İnsan, her şeyiyle sınırlıdır. Allah ise, sınırsızdır. Sınırlı olan sınırsız olanı idrâk ve ihâta edemez. “Bâtın” ismi, “Zâhir” ismiyle beraber değerlendirilmelidir."),

            Asmaa(isFaved: false, id: 77, name: "El-Vâlî", arabic: "الوَالِي", shortText: "Her şeyi tek başına idare eden.", description:"El-Vâlî: Kâinatın tek hâkimi, yöneticisi demektir. Allah Teâlâ, bu büyük evreni ve her an meydana gelen bütün olayları tek başına yönetendir. Yaratıkların işlerini yerine koyandır. Bütün varlıkların tek hükümdârı olup onlar üzerinde istediği şekilde tasarrufta bulunandır. Dirilten ve öldüren O’dur. Hiç bir şey O’nun tasarrufunun dışında kalmaz."),

            Asmaa(isFaved: false, id: 78, name: "El-Müteâlî", arabic: "المُتَعَالِ", shortText: "Aklın mümkün gördüğü her şeyden, her hâl ve tavırdan münezzeh olan.", description:"El-Müteâlî: İzzet, şeref ve hükümranlık bakımından en yüce demektir. Allah Teâlâ, yaratılmışlar hakkında aklın mümkün gördüğü her şeyden, her hal ve tavırdan yücedir. Zât, sıfat ve fiilleri açısından yaratılmışlara benzemekten, denk ve ortağı bulunmaktan yücedir."),

            Asmaa(isFaved: false, id: 79, name: "El-Berr", arabic: "البَرُّ", shortText: "Kullarına iyilik ve ihsanı, nimetleri bol olan.", description:"El-Berr: İyilik ve bahşişi çok olan; va’dini yerine getiren demektir. Allah Teâlâ, kulları hakkında kolaylık isteyendir. Yaratıklarına karşı rahmet ve mağfireti; lütuf ve ihsânı bol olandır. Kullarının hep iyiliğini ister, kötülüklerini ve zorluk çekmelerini istemez. Yapılan kötülüklerin çoğunu bağışlar, örtbas eder."),

            Asmaa(isFaved: false, id: 80, name: "Et-Tevvâb", arabic: "التَّوَّابُ", shortText: "Tövbeleri kabul eden.", description:"Et-Tevvâb: Tövbe eden kullarının tövbelerini kabul eden ve tövbede muvaffak kılan demektir. Allah Teâlâ, kullarını tövbeye sevkeden ve tövbelerini kabul edendir. Kendisine yönelen kullarının günahlarını affedendir. Tövbeleri kabul edip günahları bağışlayandır. Kul, işlediği günahlardan pişman olur, tövbeye yönelirse Allah onu tövbesinde başarılı kılar ve tövbesini kabul eder."),

            Asmaa(isFaved: false, id: 81, name: "El-Müntakim", arabic: "المُنْتَقِمُ", shortText: "Suçluları adaletiyle cezalandırıp intikam alan.", description:"El-Müntakim: Suçlulara, adâleti ile hak ettikleri cezayı veren demektir. Allah Teâlâ, suçluları hemen cezalandırmaz. Onları çeşitli yollarla uyarır. Yanlış davranışından dönmesi için kendisine fırsat ve yeterli zaman verir. Tövbe etmeyenleri cezalandırır. Fakat bu cezalandırma kendisi için değildir; zulüm ve gadre uğrayanlar içindir. Allah, dostlarından değil, düşmanlarından intikam alır."),

            Asmaa(isFaved: false, id: 82, name: "El-Afüvv", arabic: "العَفُوُّ", shortText: "Affı ve rahmeti çok olan, bağışlayan.", description:"El-Afüvv: Hiç bir sorumluluk kalmayacak şekilde günahları affeden demektir. Allah Teâlâ, günahları kökünden kazıyıp tamamen yok eder. Kirâmen kâtibin meleklerinin kayıtlarını siler. Hatırlayıp mahçup olmasınlar diye kullarına işledikleri günahları da unutturur. Bu isimden nasip alan kul, bir taraftan devamlı Allah’tan af diler, diğer taraftan ümitsizliğe kapılmaz. Kullara karşı da çok affedici olur."),

            Asmaa(isFaved: false, id: 83, name: "Er-Raûf", arabic: "الرَّءُوفُ", shortText: "Pek acıyan, lütuf ve merhametle pek esirgeyen.", description:"Er-Raûf: Çok şefkatli ve merhametli demektir. Allah Teâlâ, kullarına karşı ileri derecede merhamet ve şefkat sahibidir. Kullarının sıkıntılarını ortadan kaldırır. Allah kullarına akıl ve iyiyi kötüyü ayırt etme yeteneği vermiştir. Kullarını, işledikleri suçlardan dolayı hemen cezalandırmaz. Onlara hatalarından dönmesi için fırsat tanır. İnanan kullarının kusurlarını bağışlar, iyi amellerine fazlasıyla mükâfât verir."),

            Asmaa(isFaved: false, id: 84, name: "Mâlikü’l-Mülk", arabic: "مَالِكُ", shortText: "Mülkün ebedi sahibi olan.", description:"Mâlikü’l-Mülk: Mülkün gerçek sâhibi; bütün varlık âleminin tek hâkimi demektir. Allah Teâlâ, bütün kâinatın tek sâhibi ve mâlikidir. Mülkünde istediği gibi tasarruf eder. Dilediğine mülk verir, dilediğine vermez. Dilediğine az verir, dilediğine çok verir. Mutlak hükümranlık O’na aittir. Bu isimden nasip alan kulda mal ve mülkün emânet olduğu şuuru yerleşir. Mal ve mülkü nasıl kullanacağını bilir; israf ve cimrilikten uzak durur. Nimet verene şükrünü tam yapar."),
            
            Asmaa(isFaved: false, id: 85, name: "Zü’l- Celal-i ve’l-İkram", arabic: "ذُو الجَلَالِ، وَالإِكْرَامِ", shortText: "Her türlü büyüklüğün, her türlü keremin sahibi olan.", description:"Zü’l- Celal-i ve’l-İkram: Ululuk ve ikrâm sahibi demektir. Allah Teâlâ, yaratıkları tarafından yüceltilmeye ve övülmeye lâyık olandır. Kullarından dilediklerine, kendisine samimiyetle kulluk vazifelerini yapmayı sağlayan, mânevî derecelerini yükselten, dünyada ve âhirette onlara bol lütuflarda bulunandır. Ne kadar büyüklük, ululuk, yücelik varsa, hepsi Allah’a mahsustur."),
            
            Asmaa(isFaved: false, id: 86, name: "El-Muksıt", arabic: "المُقْسِطُ", shortText: "Bütün işleri birbirine uygun ve denk yapan.", description:"El-Muksıt: Adâlet sahibi; bütün işlerini denk, birbirine uygun ve yerli yerinde yapan demektir. Allah Teâlâ, adâletle hükmedendir. En üstün adâlet ve merhamet sahibidir. Mazlumların haklarını zâlimlerden alandır. Dünyada dost düşman ayırımı yapmadan bütün kullarına rızık verir. Âhirette, dostları, yaptıklarının karşılığını fazlasıyla alacak, düşmanları ise sadece yaptıklarının karşılığı bir cezaya çarptırılacaklardır."),
            
            Asmaa(isFaved: false, id: 87, name: "El-Câmî", arabic: "الجَامِعُ", shortText: "İstediğini istediği zaman istediği yerde toplayan.", description:"El-Câmî: İstediğini istediği zaman istediği yerde toplayan demektir. Allah Teâlâ, birbirine benzeyen şeyleri ve benzemeyen zıt şeyleri bir araya getirip toplayandır. Kıyâmet günü hesaba çekmek için yaratıkları toplayandır. Bütün iyilikleri, güzellikleri ve övgüleri zâtında toplayandır. Tabiatları zıt birçok unsuru bir araya getirendir. İnsanları birbirlerine sevdirip kalpleri ısındırandır."),

            Asmaa(isFaved: false, id: 88, name: "El-Ganîyy", arabic: "الغَنِيُّ", shortText: "Çok zengin olan.", description:"El-Ganîyy: Çok zengin olan; hiç bir şeye muhtaç olmayan demektir. Allah Teâlâ, her şey kendisine muhtaç olan; kendisi hiç bir şeye muhtaç olmayandır. Zât ve sıfatlarında her türlü ihtiyaçtan uzak olandır. Çok zengindir, hiçbir şeye ihtiyacı yoktur. Ama bütün varlıklar her konuda O’na muhtaçtır."),

            Asmaa(isFaved: false, id: 89, name: "El-Muğnî", arabic: "المُغْنِيُّ", shortText: "İstediğini zengin eden.", description:"El-Muğnî: İstediğini zengin eden demektir. Allah Teâlâ, dilediği kulun her türlü ihtiyacını karşılayandır. Fakir kullarını lütuf ve ihsânıyla zenginleştirir. Kanâat duygusu lütfedip gönül zenginliğine eriştirir. Kulun hal ve davranışlarını rızası yönüne yönlendirerek mânevî bakımdan zenginleştirir."),

            Asmaa(isFaved: false, id: 90, name: "El-Mânî", arabic: "المَانِعُ", shortText: "Bazı şeylerin meydana gelmesine müsaade etmeyen, engelleyen.", description:"El-Mânî:; Dilemediği şeylerin gerçekleşmesine izin vermeyen; kötü şeylere engel olan demektir. Allah Teâlâ, bazı isteklerin gerçekleşmesine müsaade etmez. Bütün isteklerimiz, Allah’ın dilemesi ve takdiriyle gerçekleşir. O’nun dilemediği bir şey olmaz. Dilediği şey de olur. Allah Teâlâ, sevdiği kullarının bazı kötü isteklerine engel olmak suretiyle onları zarardan korur."),

            Asmaa(isFaved: false, id: 91, name: "Ed-Dâr", arabic: "الضَّارُ", shortText: "Elem ve zarar verecek şeyleri yaratan, hüsrana ugratan.", description:"Ed-Dâr: Zarar veren; elem ve zarar verici şeyleri yaratan demektir. Allah Teâlâ, bir kuluna her hangi bir zarar vermeyi dilerse, hiç kimse ona fayda veremez. Fayda vermek istediği kimseye de kimse zarar veremez. “Dârr” ismi, “Nâfi’” ismiyle beraber değerlendirilmelidir."),

            Asmaa(isFaved: false, id: 92, name: "En-Nâfi", arabic: "النَّافِعُ", shortText: "Hayır ve menfaat verecek şeyleri yaratan.", description:"En-Nâfi: Fayda veren; dilediği kuluna hayırlı ve faydalı olanı veren demektir. Allah Teâlâ, zararlı gibi görünen her şeyi sezilmez yollarla faydalı hale getirendir. Çaresizlerin imdadına yetişendir. Kulunu hayra ve iyiliğe yöneltendir. “Nâfi” ismi, “Dârr” ismiyle beraber değerlendirilmelidir"),

            Asmaa(isFaved: false, id: 93, name: "En-Nûr", arabic: "النُّورُ", shortText: "Alemleri nurlandıran.", description:"En-Nûr: Nurlandıran, ışık veren, nur kaynağı; âlemleri nurlandıran; istediği simalara, zihinlere ve gönüllere nur yağdıran demektir. Allah Teâlâ, varlığı apaçık olandır. Nuru yaratan, onunla gökleri ve yeri aydınlatandır. Kulunun kalbini, gönlünü îmân nuruyla aydınlatarak hidâyete ermesini ve doğruyu bulmasını sağlayandır."),

            Asmaa(isFaved: false, id: 94, name: "El-Hâdî", arabic: "الهَادِي", shortText: "Hidayete ve doğru yola erdiren.", description:"El-Hâdî: Hidâyeti yaratan; istediği kulunu muradına erdiren, hayırlı yollara muvaffak kılan demektir. Allah Teâlâ, inanacak kalplerde hidâyeti yaratandır. Ebedî mutluluğu sağlayacak doğru yolu gösteren ve doğru yola ulaştırandır. Yolunu şaşırmışlara rehberlik edendir."),

            Asmaa(isFaved: false, id: 95, name: "El-Bedî", arabic: "البَدِيعُ", shortText: "Örneksiz, misilsiz, hayret verici nice âlemler icad eden.", description:"El-Bedî: Varlıkları, eşi, benzeri ve örneği olmaksızın, sanatkârane bir şekilde yaratan demektir. Allah Teâlâ, her şeyi, bir numûnesi, benzeri olmaksızın yaratandır. Bu yaratma da eşsiz ve benzersiz bir yaratmadır. Yani akıllara durgunluk verecek derecede kusursuz ve mükemmel yaratmadır. Allah, zâtında, sıfatlarında ve fiillerinde benzeri görülmeyendir."),

            Asmaa(isFaved: false, id: 96, name: "El-Bâki", arabic: "البَاقِي", shortText: "Varlığının sonu bulunmayan, ebedi olan", description:"El-Bâki: Ebedî olan; varlığının sonu olmayan demektir. Allah Teâlâ, varlığı devamlı olandır. Varlığının bir başlangıcı olmadığı gibi bir sonu da yoktur. Zâtı da, sıfatları da, fiilleri de bâkîdir, ebedîdir, devamlıdır. Mü’min de her hangi bir işi Allah rızası için yapmışsa, o fiil de ebedîlik kazanır. Yani kul, öbür âlemde mükâfâtını alır."),

            Asmaa(isFaved: false, id: 97, name: "El-Vâris", arabic: "الوَارِثُ", shortText: "Servetlerin gerçek sahibi olan.", description:"El-Vâris: Varlığının sonu olmayan demektir. Allah Teâlâ, yaratılmış bütün varlıkları yok ettikten sonra bâkî kalan, mülkün gerçek sahibidir. Mülkü dilediğinden alır, dilediğine verir. Dünyada bulunan herkes ve evrende bulunan her şey fânîdir, geçicidir. İnsanlar ölümlü oldukları için sahip oldukları mal, mülk, servet de geçicidir."),

            Asmaa(isFaved: false, id: 98, name: "Er-Reşid", arabic: "الرَّشِيدُ", shortText: "Bütün işleri ezeli takdirine uygun bir nizam ve hikmet üzere sonuna ulaştıran.", description:"Er-Reşid: İrşad eden; doğru yolu gösteren demektir. Allah Teâlâ, bütün işleri isabetli olan ve hedefine ulaşandır. Her şeyi ezelî takdirine göre yürüten, bir nizam ve hikmet üzere sonuna ulaştırandır. Lüzumsuz, faydasız, boş iş yapmayandır. Fiilleri dâimâ yerinde olandır. Devamlı olarak hakka isabet edendir. Hiç kimsenin yol göstermesine muhtaç olmayandır."),

            Asmaa(isFaved: false, id: 99, name: "Es-Sabûr", arabic: "الصَّبُورُ", shortText: "Çok sabırlı olan.", description:"Es-Sabûr: Çok sabırlı demektir. Allah Teâlâ, günahkârları cezalandırma konusunda acele etmeyip lütfuyla bağışlayan ve erteleyendir. Günahkârlara mühlet tanır. Tövbe kapısını ölünceye kadar açık tutar. Kullarının af ve bağışlama dilemeleri için onlara fırsatlar tanır. Bu isimden nasip alan kul, ibâdetleri yapmada, haramlardan kaçınmada ve her türlü felâket karşısında sabırlı olur.")
        ]
        return Names
    }
}

